import type { Metadata } from "next";
import "./globals.css";
import { Button } from "@/components/ui/button";
import { Space_Grotesk } from "next/font/google";
import Image from "next/image";

const SpaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${SpaceGrotesk.className} antialiased`}>
        <div className="flex min-h-screen flex-col">
          <main className="flex-1 flex items-center justify-center">
            <div className="container max-w-2xl mx-auto px-4  text-center">
              <section>{children}</section>
            </div>
          </main>
          <footer className="border-t">
            <div className="flex items-center justify-center py-2">
              <div className="flex items-center justify-center gap-1">
                <p className="flex text-center text-sm leading-loose text-muted-foreground">
                  Created with ❤️ by{" "}
                </p>
                <ProfileButton />
              </div>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}

function ProfileButton() {
  return (
    <Button
      variant={"ghost"}
      className="rounded-full h-7 py-0 ps-0 items-center justify-center">
      <div className="flex items-center">
        <div className="w-8 aspect-square h-full p-1.5">
          <Image
            className="h-auto w-full rounded-full"
            src="https://avatars.githubusercontent.com/u/114096753?v=4"
            alt="Profile image"
            width={20}
            height={20}
            aria-hidden="true"
          />
        </div>
        <p>adii</p>
      </div>
    </Button>
  );
}
